---
apiVersion: v1
kind: Job
metadata:
  name: count_correlations_jobs
  labels:
    imageName: curated_projects
    tier: job
spec:
  # Nodes number
  parallelism: 10
  template:
    metadata:
      name: count_correlations_job
      labels:
        imageName: curated_projects
        tier: worker
    spec:
      containers:
        - name: curated_projects
          image: docker.io/ivasilyev/curated_projects:latest
          imagePullPolicy: Always
          command: ["python3", "/home/docker/scripts/curated_projects/ashestopalov/nutrition/obesity_metagenomes/5_count_correlations.py"]
          volumeMounts:
            - name: data1
              mountPath: /data1
      volumes:
        - name: data1
          hostPath:
            path: /data1
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: cpu
                    operator: In
                    values:
                    - xeon-e5-2630-v2
                    - xeon-e5-2630-v3
      restartPolicy: Never


# Deploy from master node:
# kubectl create -f count_correlations.yml

# Get pods info:
# kubectl get pods

# Get node info:
# kubectl describe pod count_correlations | grep Node:

# Get token:
# kubectl logs count_correlations | grep token

# Cleanup:
# kubectl delete pod count_correlations
