ACTIVE_NODES_NUMBER: 7
JOB_NAME: ndanilova-bwt-sk-job
MASTER_CONTAINER_NAME: ndanilova-bwt-sk-master
OUTPUT_DIR: /data2/bio/Metagenomes/custom/SCFAs_from_KEGG
OUTPUT_MASK: no_hg19
QUEUE_NAME: ndanilova-bwt-sk-queue
REFDATA: /data/reference/custom/SCFAs_from_KEGG/index/SCFAs_from_KEGG.refdata
SAMPLEDATA: /data1/bio/projects/ndanilova/colitis_crohn/colitis_esc_colitis_rem_crohn_esc_crohn_rem_srr.sampledata
WORKER_CONTAINER_NAME: ndanilova-bwt-sk-worker
