library(reshape2)
library(stats)
library(ggplot2)

df <- read.csv("res_for_R.csv", header = T, row.names = 1, sep="\t")
f.m <- melt(df, id.var = "point")
p <- ggplot(data = f.m, aes(x=variable, y=value)) + geom_boxplot(aes(fill=point)) + theme_bw()
p + facet_wrap( ~ variable, scales="free")

attach(df)

pairwise.wilcox.test(determinant_of_aminoglycoside_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_beta_lactam_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_macrolide_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(efflux_pump_complex_or_subunit_conferring_antibiotic_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_rifamycin_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_tetracycline_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_fluoroquinolone_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_fosfomycin_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(peptide_anibiotic, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_sulfonamide_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_phenicol_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_streptogramin_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_lincosamide_resistance, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_resistance_to_nucleoside_antibiotics, point, conf.level = 0.95, p.adj = "BH", paired=T)
pairwise.wilcox.test(determinant_of_resistance_to_glycopeptide_antibiotics, point, conf.level = 0.95, p.adj = "BH", paired=T)
