ACTIVE_NODES_NUMBER: 9
JOB_NAME: tgrigoreva-bwt-eps2-job
MASTER_CONTAINER_NAME: tgrigoreva-bwt-eps2-master
OUTPUT_DIR: /data2/bio/Metagenomes/custom/25_ecoli_genes
OUTPUT_MASK: no_hg19
QUEUE_NAME: tgrigoreva-bwt-eps2-queue
REFDATA: /data/reference/custom/25_ecoli_genes/index/25_ecoli_genes.refdata
SAMPLEDATA: /data1/bio/projects/tgrigoreva/ecoli_plates_suspension/ecoli_plates_suspension_reads.sampledata
WORKER_CONTAINER_NAME: tgrigoreva-bwt-ep2s-worker
