queue_name: tgrigoreva-bwt-25-queue
master_container_name: bwt-fp-master
job_name: tgrigoreva-bwt-25-job
worker_container_name: tgrigoreva-bwt-25-worker
sampledata: /data1/bio/projects/dsafina/hp_checkpoints/srr_hp_checkpoints.sampledata
refdata: /data1/bio/projects/tgrigoreva/25_ecoli_genes/index/25_ecoli_genes.refdata
mask: no_hg19
output_dir: /data1/bio/projects/tgrigoreva/25_ecoli_genes/map
