---
apiVersion: v1
kind: Pod
metadata:
  name: tgrigoreva-bwt-25-queue
  labels:
    pipeline: bwt-filtering
    tier: queue
spec:
  containers:
    - name: tgrigoreva-bwt-25-master
      image: docker.io/ivasilyev/bwt_filtering_pipeline_master:latest
      imagePullPolicy: Always
      # Paste the digested queue creation command line. Note the queue name.
      command: ["python3", "/home/docker/scripts/sampledata2jsons_queue.py", "-s", /data2/bio/Metagenomes/custom/25_ecoli_genes/2018-04-01-20-53-41.sampledata, "-c", /data/reference/custom/25_ecoli_genes/index/25_ecoli_genes.refdata, "-m", no_hg19, "-o", /data2/bio/Metagenomes/custom/25_ecoli_genes, "-q", tgrigoreva-bwt-25-queue]
      # Persistent volumes (container side)
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /data1
          name: data1
        - mountPath: /data2
          name: data2
  # Persistent volumes (host side)
  volumes:
    - name: data
      hostPath:
        path: /data
    - name: data1
      hostPath:
        path: /data1
    - name: data2
      hostPath:
        path: /data2
  restartPolicy: Never
