- hosts: kube-node
  tasks:
    - name: Perform a main run
      shell: cd /tmp && curl -fsSLO "https://raw.githubusercontent.com/ivasilyev/curated_projects/master/ashestopalov/nutrition/obesity_metagenomes/ansible/main_run.sh" && bash main_run.sh
