---
apiVersion: v1
kind: Pod
metadata:
  name: ndanilova-bwt-igc-queue
  labels:
    pipeline: bwt-filtering
    tier: queue
spec:
  containers:
    - name: ndanilova-bwt-igc-master
      image: docker.io/ivasilyev/bwt_filtering_pipeline_master:latest
      imagePullPolicy: Always
      # Paste the digested queue creation command line. Note the queue name.
      command: ["python3", "/home/docker/scripts/sampledata2jsons_queue.py", "-s", /data1/bio/projects/ndanilova/colitis_crohn/colitis_esc_colitis_rem_crohn_esc_crohn_rem_srr.sampledata, "-c", /data/reference/IGC/index/igc_v2014.03.refdata, "-m", no_hg19, "-o", /data2/bio/Metagenomes/IGC, "-q", ndanilova-bwt-igc-queue]
      # Persistent volumes (container side)
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /data1
          name: data1
        - mountPath: /data2
          name: data2
  # Persistent volumes (host side)
  volumes:
    - name: data
      hostPath:
        path: /data
    - name: data1
      hostPath:
        path: /data1
    - name: data2
      hostPath:
        path: /data2
  restartPolicy: Never
